apiVersion: v1
entries:
  sekolahlinux:
  - apiVersion: v2
    created: "2025-05-08T16:52:40.857877942Z"
    description: A Helm chart for general app
    digest: 0ec9382285ee205d61ab260ee71db78e7d6059817b97ebce2a8d37ae7b7e00a7
    home: https://github.com/unbirabka/helm-sekolahlinux
    name: sekolahlinux
    sources:
    - https://github.com/unbirabka/helm-sekolahlinux
    type: application
    urls:
    - sekolahlinux-0.1.0.tgz
    version: 0.1.0
generated: "2025-05-08T16:52:40.856300899Z"
