{{- if and .Values.server.enabled -}}
{{- $name := .Release.Name -}}
{{- $fullName := include "server.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.server.autoReload }}
    reloader.stakater.com/auto: "true"
    {{- end }}
    {{- with .Values.server.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.server.replicas }}
  replicas: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ $fullName }}
      env: {{ .Values.meta.env }}
  {{- with .Values.server.rollingUpdate }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .maxSurge }}
      maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  template:
    metadata:
      labels:
        name: {{ $fullName }}
        env: {{ .Values.meta.env }}
        version: {{ .Values.meta.version }}
        maintainer: {{ .Values.meta.maintainer }}
        managed-by: {{ .Release.Service }}
        helm-chart: {{ include "meta.chart" . }}
      annotations:
        prometheus.io/scrape: {{ .Values.server.prometheus.scrape | quote }}
        {{- if .Values.server.prometheus.scrape }}
        prometheus.io/path: {{ .Values.server.prometheus.path | quote }}
        {{- with .Values.server.prometheus.port }}
        prometheus.io/port: {{ . | quote }}
        {{- end }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.server.istio.injected | quote }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainer.enabled }}
      initContainers:
        - name: init-{{ $fullName }}
          image: "{{ .Values.initContainer.image }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          {{- with .Values.initContainer.command }}          
          command:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.initContainer.args }}
          args:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          env:
            {{- with .Values.initContainer.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- end }}
      containers:
        - name: {{ $fullName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.server.command }}
          command:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.server.args }}
          args:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
            {{- if and .Values.server.prometheus.scrape .Values.server.prometheus.port }}
            - name: prometheus
              containerPort: {{ .Values.server.prometheus.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.server.liveness.enabled }}
          {{- with .Values.server.liveness.config }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.server.readiness.enabled }}
          {{- with .Values.server.readiness.config }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.configMap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ $name }}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.server.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.configMap.enabled }}
            - name: {{ $fullName }}
              mountPath: {{ .Values.configMap.mountPath }}
              {{- with .Values.configMap.subPath }}
              subPath: {{ . }}
              {{- end }}
              readOnly: {{ .Values.configMap.readOnly }}
            {{- end }}
            {{- with .Values.server.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.server.containers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.configMap.enabled }}
        - name: {{ $fullName }}
          configMap:
            name: {{ $name }}
        {{- end }}
        {{- with .Values.server.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      restartPolicy: {{ .Values.server.restartPolicy }}
      dnsPolicy: {{ .Values.server.dnsPolicy }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
